//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploSoa.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.GerirSalaSoap")]
    public interface GerirSalaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Put(int id, string username, string password, string tag, string schedule, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PutAsync(int id, string username, string password, string tag, string schedule, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Post(int id, string username, string password, string tag, string schedule, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PostAsync(int id, string username, string password, string tag, string schedule, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GerirSalaSoapChannel : ExemploSoa.ServiceReference2.GerirSalaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GerirSalaSoapClient : System.ServiceModel.ClientBase<ExemploSoa.ServiceReference2.GerirSalaSoap>, ExemploSoa.ServiceReference2.GerirSalaSoap {
        
        public GerirSalaSoapClient() {
        }
        
        public GerirSalaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GerirSalaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerirSalaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerirSalaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public string Put(int id, string username, string password, string tag, string schedule, string status) {
            return base.Channel.Put(id, username, password, tag, schedule, status);
        }
        
        public System.Threading.Tasks.Task<string> PutAsync(int id, string username, string password, string tag, string schedule, string status) {
            return base.Channel.PutAsync(id, username, password, tag, schedule, status);
        }
        
        public string Post(int id, string username, string password, string tag, string schedule, string status) {
            return base.Channel.Post(id, username, password, tag, schedule, status);
        }
        
        public System.Threading.Tasks.Task<string> PostAsync(int id, string username, string password, string tag, string schedule, string status) {
            return base.Channel.PostAsync(id, username, password, tag, schedule, status);
        }
        
        public string Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
